### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by EddyVerbruggen** [tahir-jamil/new-translator#1]
@tahir-jamil You opened an issue on my Firebase repo about permissions (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1007), but when I asked what the actual error was, you're showing logs saying "run init() first". So PLEASE try to describe the issue accurately, and on which platform(s) you're seeing it.

**Comment by tahir-jamil** [comment]
i try to use realtime database this time and i follow the docs as explained but unable to get the required results 

hear is the error logs i have
`JS: firebase.init done
11-04 23:33:15.701  3564  3564 I PhoneWindow: isNeedChangeStatusBarColor taskInfo: [android.app.ActivityManager$RunningTaskInfo@39923ba] size: 1
11-04 23:33:15.704  3564  3564 I PhoneWindow: isNeedChangeNaviBarColor taskInfo: [android.app.ActivityManager$RunningTaskInfo@cf3126b] size: 1
JS: Error: Run init() first!`

**Comment by EddyVerbruggen** [comment]
But your report was about permissions, where did that go?

**Comment by tahir-jamil** [comment]
i have added you in repo you can do anything with this in order to make it functions 
yes its true i have faced permissions issue in morning than i left this and try to complete other functionality of this app and know its showing this let me test it so i can re create it

**Comment by EddyVerbruggen** [comment]
Well, you can try the Angular demo in the plugin repo and see what's different.

```
git clone https://github.com/EddyVerbruggen/nativescript-plugin-firebase
cd nativescript-plugin-firebase/src
npm run setupandinstall (just skip through the plugin y/n prompts you'll get as those are ignored in this case)
npm run demo-ng.android
```

**Comment by tahir-jamil** [comment]
ok

**Comment by tahir-jamil** [comment]
i just remove platform and node_modules and now its showing the error log for permission denied 
well i think it can be due to the wrong path or may be something else 
hear i am passing the path for bucket
`getData() {
    firebase.getValue('companies')
      .then(result => console.log(JSON.stringify(result)))
      .catch(error => console.log("Error: " + error));
  }`

also you can use teamviewer and solve this issue on my system if you want
well its hurting but i just want to solve this nothing more
![screen shot 2018-11-05 at 12 46 36 am](https://user-images.githubusercontent.com/40952630/47969171-5c6a0100-e095-11e8-9b73-cb0e344538ec.png)

**Comment by tahir-jamil** [comment]
also you can use teamviewer and solve this issue on my system if you want
